### ISSUE TITLE
Fix error while importing encodings in singularity client

### ISSUE THREAD

**Issue by dgasull** [bsc-dom/dataclay-orchestration#1]
Following error appears while trying to register model or get stubs (use python entry point in singularity client):
```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
```
Can be reproduced by running `full_demo.sh` in https://github.com/bsc-dom/dataclay-demos/tree/singularity_demo/singularity-hellopeople-python

**Comment by pierlauro** [comment]
I saw the error earlier, it was solved by importing the `PYTHONPATH` as the script is doing, and by using the system python interpreter instead of the virtual environment one.

I will check the job script

**Comment by pierlauro** [comment]
The error is solved by importing into the container the `PYTHONPATH`, `LD_LIBRARY_PATH` and `PATH` variables set by the *DATACLAY/2.1* module.

```bash
# Loading the module to get correct values of env variables

user@MareNostrum:~> module load DATACLAY/2.1

user@MareNostrum:~> echo $PYTHONPATH
/apps/PYTHON/3.7.4/INTEL/lib/python3.7/site-packages:/home/dataclayusr/dataclay/build/lib:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7/site-packages:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7

user@MareNostrum:~> echo $LD_LIBRARY_PATH
/usr/lib64:/apps/PYTHON/3.7.4/INTEL/lib:/apps/GCC/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0:/apps/GCC/5.4.0/lib64:/apps/LIBSPATIALINDEX/1.9.0/INTEL/lib:/apps/INTEL/2017.4/mkl/lib/intel64:/apps/INTEL/2017.4/impi/2017.3.196/lib64:/apps/INTEL/2017.4/lib/intel64

user@MareNostrum:~> echo $PATH
/apps/PYTHON/3.7.4/INTEL/bin:/apps/SINGULARITY/3.5.2/bin:/apps/GCC/5.4.0/bin:/apps/DATACLAY/2.1/scripts:/apps/JDK/8u131/bin:/apps/modules/bsc/bin:/apps/INTEL/2017.4/impi/2017.3.196/bin64:/apps/INTEL/2017.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lpp/mmfs/bin

# Entering the container
user@MareNostrum:~> singularity exec $DATACLAY_HOME/images/client.sif bash

# Expected to fail - wrong env variables

Singularity> python3
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f6a9a16e240 (most recent call first):
Aborted

# Setting correct env variables

Singularity> export PYTHONPATH=/apps/PYTHON/3.7.4/INTEL/lib/python3.7/site-packages:/home/dataclayusr/dataclay/build/lib:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7/site-packages:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7
Singularity> export LD_LIBRARY_PATH=/usr/lib64:/apps/PYTHON/3.7.4/INTEL/lib:/apps/GCC/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0:/apps/GCC/5.4.0/lib64:/apps/LIBSPATIALINDEX/1.9.0/INTEL/lib:/apps/INTEL/2017.4/mkl/lib/intel64:/apps/INTEL/2017.4/impi/2017.3.196/lib64:/apps/INTEL/2017.4/lib/intel64
Singularity> export PATH=/apps/PYTHON/3.7.4/INTEL/bin:/apps/SINGULARITY/3.5.2/bin:/apps/GCC/5.4.0/bin:/apps/DATACLAY/2.1/scripts:/apps/JDK/8u131/bin:/apps/modules/bsc/bin:/apps/INTEL/2017.4/impi/2017.3.196/bin64:/apps/INTEL/2017.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lpp/mmfs/bin

# The interpreter works

Singularity> python3
Python 3.7.4 (default, Oct 29 2019, 13:10:00) 
[GCC Intel(R) C++ gcc 5.4 mode] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

```

A possible solution to overcome that is creating a file with the needed variables and mount it into the container in order to be sourced at startup ([MORE DETAILS](https://github.com/singularityhub/singularity-compose/issues/25#issuecomment-582453260)).
```bash
user@MareNostrum:~> echo export PYTHONPATH=$PYTHONPATH > python_env.sh

user@MareNostrum:~> echo export LD_LIBRARY_PATH=$LD_LIBRARY_PATH >> python_env.sh

user@MareNostrum:~> echo export PATH=$PATH >> python_env.sh 

user@MareNostrum:~> singularity exec -B ./python_env.sh:/.singularity.d/env/python_env.sh $DATACLAY_HOME/images/client.sif bash
Singularity> python3
Python 3.7.4 (default, Oct 29 2019, 13:10:00) 
[GCC Intel(R) C++ gcc 5.4 mode] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

```

**Comment by dgasull** [comment]
Still not working. 

Module lua contains PYTHONPATH,LD_LIBRARY_PATH and PATH environment variables in order to have also needed libraries loaded by the module 

I've modified `deploy_dataclay.sh` to append PYTHONPATH, LD_LIBRARY_PATH and PATH into `.dataClay/job$SLURM_JOBID/client/env.sh` and modified the `DATACLAYCMD_SINGULARITY` environment variable to mount that file as you specified: 

```eval srun --exclusive --ntasks 1 --nodes 1 singularity run -B \$HOME/.dataClay/job\$SLURM_JOBID/client/env.sh:/.singularity.d/env/python_env.sh " .. DATACLAY_HOME .. "/images/client.sif ```

I had to add $PATH, $PYTHONPATH and $LD_LIBRARY_PATH in env.sh to append to singularity environemnt variables (you can see it in `deploy_dataclay.sh`)
 If I don't do that then /home/dataclayusr/dataclay/entrypoints/dataclay-python-entry-point is not found. 

```
# Add escaped $PATH to add also env. variables from singularity container
echo "export PATH=\$PATH:$PATH" >> $JOB_ENV_FILE
echo "export PYTHONPATH=\$PYTHONPATH:$PYTHONPATH" >> $JOB_ENV_FILE
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $JOB_ENV_FILE
```

So in `env.sh` mounted in singularity run for client you have: 
```
export PATH=/apps/DATACLAY/2.1/scripts:/apps/PYTHON/3.7.4/INTEL/bin:/apps/SINGULARITY/3.5.2/bin:/apps/GCC/5.4.0/bin:/apps/JDK/8u131/bin:/apps/modules/bsc/bin:/apps/INTEL/2017.4/impi/2017.3.196/bin64:/apps/INTEL/2017.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lpp/mmfs/bin:/home/bsc25/bsc25731/bin:$PATH
export PYTHONPATH=/apps/PYTHON/3.7.4/INTEL/lib/python3.7/site-packages:/home/dataclayusr/dataclay/build/lib:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7/site-packages:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7:$PYTHONPATH
export LD_LIBRARY_PATH=/usr/lib64:/apps/PYTHON/3.7.4/INTEL/lib:/apps/GCC/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0:/apps/GCC/5.4.0/lib64:/apps/LIBSPATIALINDEX/1.9.0/INTEL/lib:/apps/INTEL/2017.4/mkl/lib/intel64:/apps/INTEL/2017.4/impi/2017.3.196/lib64:/apps/INTEL/2017.4/lib/intel64:$LD_LIBRARY_PATH
```
Then I have the error:
```
Traceback (most recent call last):
  File "/apps/PYTHON/3.7.4/INTEL/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/apps/PYTHON/3.7.4/INTEL/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/dataclayusr/dataclay/build/lib/dataclay/__init__.py", line 7, in <module>
    from dataclay.commonruntime.Runtime import getRuntime
  File "/home/dataclayusr/dataclay/build/lib/dataclay/commonruntime/Runtime.py", line 71, in <module>
    from dataclay.DataClayObject import DataClayObject  # Import after runtime to avoid circular-imports (runtime is already defined here)
  File "/home/dataclayusr/dataclay/build/lib/dataclay/DataClayObject.py", line 28, in <module>
    from dataclay.commonruntime.ExecutionGateway import ExecutionGateway, class_extradata_cache_client, \
  File "/home/dataclayusr/dataclay/build/lib/dataclay/commonruntime/ExecutionGateway.py", line 14, in <module>
    from dataclay.util.management.classmgr.MetaClass import MetaClass
  File "/home/dataclayusr/dataclay/build/lib/dataclay/util/management/classmgr/MetaClass.py", line 6, in <module>
    from dataclay.util.MgrObject import ManagementObject
  File "/home/dataclayusr/dataclay/build/lib/dataclay/util/MgrObject.py", line 7, in <module>
    from dataclay.commonruntime.Initializer import size_tracking
  File "/home/dataclayusr/dataclay/build/lib/dataclay/commonruntime/Initializer.py", line 13, in <module>
    import logging.config
  File "/apps/PYTHON/3.7.4/INTEL/lib/python3.7/logging/config.py", line 30, in <module>
    import logging.handlers
  File "/apps/PYTHON/3.7.4/INTEL/lib/python3.7/logging/handlers.py", line 28, in <module>
    import queue
  File "/apps/PYTHON/3.7.4/INTEL/lib/python3.7/queue.py", line 16, in <module>
    from _queue import Empty
ImportError: /apps/PYTHON/3.7.4/INTEL/lib/libpython3.7m.so.1.0: undefined symbol: __intel_skx_avx512_memset
```
@pierlauro Please can you run the `full_demo.sh` script and see what it's happening? Because is different the way you did it than doing it in sbatch (for env. variables expansion). 

Another question, since I am already appending singularity env- variables using $PATH do we need to specify "/home/dataclayusr/dataclay/build/lib/" and so on in the PATH?

**Comment by dgasull** [comment]
Otherwise, try to do your steps and `import dataclay`: 

```
# Setting correct env variables

Singularity> export PYTHONPATH=/apps/PYTHON/3.7.4/INTEL/lib/python3.7/site-packages:/home/dataclayusr/dataclay/build/lib:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7/site-packages:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7
Singularity> export LD_LIBRARY_PATH=/usr/lib64:/apps/PYTHON/3.7.4/INTEL/lib:/apps/GCC/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0:/apps/GCC/5.4.0/lib64:/apps/LIBSPATIALINDEX/1.9.0/INTEL/lib:/apps/INTEL/2017.4/mkl/lib/intel64:/apps/INTEL/2017.4/impi/2017.3.196/lib64:/apps/INTEL/2017.4/lib/intel64
Singularity> export PATH=/apps/PYTHON/3.7.4/INTEL/bin:/apps/SINGULARITY/3.5.2/bin:/apps/GCC/5.4.0/bin:/apps/DATACLAY/2.1/scripts:/apps/JDK/8u131/bin:/apps/modules/bsc/bin:/apps/INTEL/2017.4/impi/2017.3.196/bin64:/apps/INTEL/2017.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lpp/mmfs/bin

# The interpreter works

Singularity> python3
Python 3.7.4 (default, Oct 29 2019, 13:10:00) 
[GCC Intel(R) C++ gcc 5.4 mode] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dataclay       **********<----- ! *****************

**Comment by pierlauro** [comment]
> Otherwise, try to do your steps and `import dataclay`:
> 
> ```
> # Setting correct env variables
> 
> Singularity> export PYTHONPATH=/apps/PYTHON/3.7.4/INTEL/lib/python3.7/site-packages:/home/dataclayusr/dataclay/build/lib:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7/site-packages:/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7
> Singularity> export LD_LIBRARY_PATH=/usr/lib64:/apps/PYTHON/3.7.4/INTEL/lib:/apps/GCC/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0:/apps/GCC/5.4.0/lib64:/apps/LIBSPATIALINDEX/1.9.0/INTEL/lib:/apps/INTEL/2017.4/mkl/lib/intel64:/apps/INTEL/2017.4/impi/2017.3.196/lib64:/apps/INTEL/2017.4/lib/intel64
> Singularity> export PATH=/apps/PYTHON/3.7.4/INTEL/bin:/apps/SINGULARITY/3.5.2/bin:/apps/GCC/5.4.0/bin:/apps/DATACLAY/2.1/scripts:/apps/JDK/8u131/bin:/apps/modules/bsc/bin:/apps/INTEL/2017.4/impi/2017.3.196/bin64:/apps/INTEL/2017.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lpp/mmfs/bin
> 
> # The interpreter works
> 
> Singularity> python3
> Python 3.7.4 (default, Oct 29 2019, 13:10:00) 
> [GCC Intel(R) C++ gcc 5.4 mode] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import dataclay       **********<----- ! *****************
> ```

This is because in the client image the venv is still created with python 3.6 (the client image was generated before we switched to python 3.7) so the `PYTHONPATH` is pointing to the non-existent `/home/dataclayusr/dataclay/dataclay_venv/lib/python3.7/site-packages` . We didn't realize until now because we were using just the java part of `dataclaycmd`.

Updating the image should also solve `undefined symbol: __intel_skx_avx512_memset` since the issue is not appearing in the dspython (venv in python 3.7).

I will take care of updating the images.

**Comment by pierlauro** [comment]
Solved!

- The first error (`undefined symbol: __intel_skx_avx512_memset`) was caused because in `deploy_dataclay.sh` the container's PYTHONPATH was prepended to the right PYTHONPATH (solved by appending it).

- A subsequent error (`ImportError: libffi.so.4: cannot open shared object file` caused by `import ctypes`) was solved by explicitly mounting `/usr/lib64' into the container. By default, singularity is not letting any `/usr` subdirectory being visible in containers.
